# Generated by Django 3.1.5 on 2021-01-21 11:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('CMP', 'Completed'), ('PRC', 'Processing')], default='PRC', max_length=3)),
                ('file', models.FileField(upload_to='csv/')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modified', models.DateField(default=datetime.date.today)),
                ('column_separator', models.CharField(choices=[('C', 'Comma (,)'), ('P', 'Point (.)'), ('S', 'Semicolon (;)')], max_length=1)),
                ('string_character', models.CharField(choices=[('D', 'Double-quote (")'), ('S', "Single quote (')")], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('NM', 'Full name'), ('JB', 'Job'), ('EM', 'Email'), ('DM', 'Domain'), ('PH', 'Phone number'), ('CM', 'Company'), ('TX', 'Text'), ('IN', 'Integer'), ('AD', 'Address'), ('DT', 'Date')], max_length=2)),
                ('range_from', models.IntegerField(default=None, null=True)),
                ('range_to', models.IntegerField(default=None, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_app.schema')),
            ],
        ),
    ]
