# Generated by Django 3.1.5 on 2021-01-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
