# Generated by Django 3.1.5 on 2021-01-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0003_auto_20210124_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='range_from',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='range_to',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
