# Generated by Django 3.1.5 on 2021-01-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0005_auto_20210124_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csv_app.schema'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(blank=True, upload_to='csv/'),
        ),
    ]
