# Generated by Django 3.1.5 on 2021-01-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0006_auto_20210124_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='csv/'),
        ),
    ]
